# Build Stage
FROM node:lts-alpine as build-stage
WORKDIR /syncer-frontend
COPY ./frontend/spotifysyncer/package*.json ./
RUN npm install
COPY ./frontend/spotifysyncer/ .


ENTRYPOINT ["npm", "run", "test:prod"]