# Build Stage
FROM node:lts-alpine as build-stage
WORKDIR /syncer-frontend
COPY ./frontend/spotifysyncer/package*.json ./
RUN npm install
COPY ./frontend/spotifysyncer/ .
RUN npm run build

# Production Deployment Stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /syncer-frontend/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]