version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    volumes:
      - ./backend/spotifysyncer:/spotifysyncer/backend/spotifysyncer
    ports:
      - 8001:8000
    command: [ 'bash', '-c', 'gunicorn --bind :8000 --workers 4 --reload wsgi:application' ]
    depends_on:
      - postgres
      - initializer
  initializer:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    volumes:
      - ./backend/spotifysyncer:/spotifysyncer/backend/spotifysyncer
    command: [ 'bash', '-c', 'python3 manage.py migrate && python3 manage.py runscript initializer' ]
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=spotifysyncer
    ports:
      - 5432:5432
  frontend:
    build:
      dockerfile: Dockerfile.frontend.dev
      context: .
    ports:
      - 4436:4436
    volumes:
      - ./frontend/spotifysyncer:/syncer-frontend

volumes:
  postgres_data: