version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - ASPNETCORE_URLS=https://+;http://+;
    volumes:
      - .:/src
    ports:
      - 5104:5104
    command: ["dotnet", "watch"]
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=spotifysyncer
    ports:
      - 5432:5432
#  rabbit:
#    image: rabbitmq:3.11
#    hostname: rabbit
#    volumes:
#      - rabbitmq:/var/lib/rabbitmq
#    environment:
#      - RABBITMQ_DEFAULT_USER=admin
#      - RABBITMQ_DEFAULT_PASS=bigpassword

volumes:
  postgres_data:
  rabbitmq: